version: "3.9"    # syntax version

services:
  app:
    build:
      context: .          # build in current directory
    ports:
      - "8000:8000"       # local:container
    volumes:
      - ./app:/app        # system:container
    command: >            
      sh -c "python manage.py runserver 0.0.0.0:8000"
