
services:
  app:
    build:
      context: .          # build in current directory
      args:
        - DEV=true        # use DEV argument when running thorugh docker-compose
    ports:
      - "8000:8000"       # local:container
    volumes:
      - ./app:/app        # system:container
    command: >            
      sh -c "python manage.py runserver 0.0.0.0:8000"
